from enum import Enum


class CargoType(str, Enum):
    VEHICLE = "VEHICLE"
    CONTAINER = "CONTAINER"
    MISCELLANEOUS = "MISCELLANEOUS"
    TRAILER = "TRAILER"


class MiscCargoType(str, Enum):
    BULK = "BULK"
    PACKAGE = "PACKAGE"
    COIL = "COIL"


class CargoStatus(str, Enum):
    IMPORTED = "IMPORTED"
    ARRIVED = "ARRIVED"
    CLASSIFIED = "CLASSIFIED"
    ASSIGNED = "ASSIGNED"
    STORED = "STORED"
    RETRIEVAL_REQUESTED = "RETRIEVAL_REQUESTED"
    TO_SCANNER = "TO_SCANNER"
    SCANNED = "SCANNED"
    RELEASE_AUTHORIZED = "RELEASE_AUTHORIZED"
    RETRIEVED = "RETRIEVED"
    DEPARTED = "DEPARTED"
    ARCHIVED = "ARCHIVED"


class ZoneType(str, Enum):
    VEHICLE_YARD = "VEHICLE_YARD"
    CONTAINER_YARD = "CONTAINER_YARD"
    PACKAGE_AREA = "PACKAGE_AREA"
    COIL_AREA = "COIL_AREA"
    BULK_SILO_AREA = "BULK_SILO_AREA"


class PositionType(str, Enum):
    VEHICLE_SLOT = "VEHICLE_SLOT"
    CONTAINER_SLOT = "CONTAINER_SLOT"
    PACKAGE_STACK = "PACKAGE_STACK"
    COIL_SLOT = "COIL_SLOT"
    SILO = "SILO"


class AllocationStatus(str, Enum):
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"
    CANCELLED = "CANCELLED"


class MovementAction(str, Enum):
    ALLOCATED = "ALLOCATED"
    MOVED = "MOVED"
    RETRIEVAL_REQUESTED = "RETRIEVAL_REQUESTED"
    SENT_TO_SCANNER = "SENT_TO_SCANNER"
    SCANNED = "SCANNED"
    RELEASED = "RELEASED"
    RETRIEVED = "RETRIEVED"
    OVERRIDE = "OVERRIDE"