"""initial database structure

Revision ID: 1d6313a88c97
Revises: 
Create Date: 2026-09-12 18:38:36.001196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6313a88c97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_of_lading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bl_number', sa.String(), nullable=False),
    sa.Column('cargo_nature', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('gross_weight', sa.Float(), nullable=True),
    sa.Column('package_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bl_number')
    )
    op.create_table('storage_zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('zone_type', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cargo_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_type', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('bl_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bl_id'], ['bill_of_lading.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('position_code', sa.String(), nullable=True),
    sa.Column('max_weight', sa.Float(), nullable=True),
    sa.Column('current_weight', sa.Float(), nullable=True),
    sa.Column('occupied', sa.Boolean(), nullable=True),
    sa.Column('accessibility_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['storage_zone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_code')
    )
    op.create_table('allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('allocated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo_unit.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['storage_position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_unit_id', sa.Integer(), nullable=True),
    sa.Column('chassis_number', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('loaded_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_unit_id'], ['cargo_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chassis_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_table('allocation')
    op.drop_table('storage_position')
    op.drop_table('cargo_unit')
    op.drop_table('storage_zone')
    op.drop_table('bill_of_lading')
    # ### end Alembic commands ###
